### ISSUE TITLE
Support for Space Navigator via spacenavd

### ISSUE THREAD

**Issue by hammerandtongs** [flathub/org.openscad.OpenSCAD#14]
I believe OpenSCAD is affected by the lack of support for the spnav socket in flatpak like Blender and FreeCAD.

https://github.com/flatpak/flatpak/issues/3541

**Comment by t-paul** [comment]
The joystick driver seems to work fine, wenn allowing access to the joystick device:
```
flatpak run --device=all org.openscad.OpenSCAD
```

**Comment by hfiguiere** [comment]
the spnav is not accessed through a standard device. It's accessed through a socket.

**Comment by t-paul** [comment]
Without `spacenavd` installed, the Space Mouse is detected and configured as multi-axis joystick available through `/dev/input/js0` which is supported by OpenSCAD. I'm sure, I wrote the code and I just tested with my Space Mouse Wireless. This works with the command above.

**Comment by hfiguiere** [comment]
Adding `--device=all` would acceptable for this situation.

**Comment by t-paul** [comment]
Beta version supports spacenavd now. See main [README.md](https://github.com/flathub/org.openscad.OpenSCAD) for installation instructions.
