### ISSUE TITLE
Not able to set center of rotation/origin by doubleclick

### ISSUE THREAD

**Issue by Knochi** [flathub/org.openscad.OpenSCAD#19]
I'm on Steamdeck:

Operating System: SteamOS 3.4.6
KDE Plasma Version: 5.26.1
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 5.13.0-valve36-1-neptune (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0405
Memory: 14,5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405
Manufacturer: Valve
Product Name: Jupiter
System Version: 1

OpenSCAD Version: 2021.01
System information: Linux 5.13.0-valve36-1-neptune #1 SMP PREEMPT Mon, 19 Dec 2022 23:39:41 +0000 x86_64 KDE Flatpak runtime 8 CPUs 14.47 GB RAM
User Agent: OpenSCAD/2021.01 (Linux x86_64; KDE Flatpak runtime)
Compiler: GCC "11.2.0" 64bit
MinGW build: No
Debug build: No
Boost version: 1_78
Eigen version: 3.3.9
CGAL version, kernels: 4.14.3, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
OpenCSG version: OpenCSG 1.5.0
Qt version: 5.15.8
QScintilla version: 2.11.6
InputDrivers: 
GLib version: 2.68.4
lodepng version: 20180910
libzip version: 1.7.3
fontconfig version: 2.13.1
freetype version: 2.11.0
harfbuzz version: 3.0.0
cairo version: 1.16.0
lib3mf version: 1.8.1
Application Path: /app/bin
Documents Path: /home/deck/.local/share
User Documents Path: /home/deck/Documents
Resource Path: /app/share/openscad
User Library Path: /home/deck/.local/share/OpenSCAD/libraries
User Config Path: /home/deck/.var/app/org.openscad.OpenSCAD/config/OpenSCAD
Backup Path: /home/deck/.local/share/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
/home/deck/.local/share/OpenSCAD/libraries
/app/share/openscad/libraries

**Comment by t-paul** [comment]
Fixed via https://github.com/openscad/openscad/pull/3661 after the release.

**Comment by Knochi** [comment]
Can't it be patched in the flathub release?

**Comment by t-paul** [comment]
While doing dependency updates, I've backported part of the fix as this was a single line.
I hope this works, otherwise the answer is: no, unless someone else finds the time for providing a patch.
